### ISSUE TITLE
Integrate Prometheus library into IF model

### ISSUE THREAD

**Issue by rossf7** [greenscale-nandesh/if-unofficial-models#2]
The Kepler plugin will be developed in TypeScript and will need to query Prometheus to access Kepler metrics.

Sebastien has investigated and suggested using this library.
https://github.com/samber/prometheus-query-js

**Comment by greenscale-nandesh** [comment]
Prometheus query for Kepler container
 
`"expr": "( sum(\n      increase(\n         (kepler_container_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[24h:1m])\n      )\n   ) * $watt_per_second_to_kWh \n) * $natural_gas",`
